---
sudo: required
language: python
services:
  - docker
before_install:
  - docker pull selenium/standalone-firefox
  - docker pull selenium/standalone-chrome
install:
  - pip install tox
script:
  - make tests
